# SPDX-FileCopyrightText: 2023 German Aerospace Center (DLR), Helmholtz-Zentrum Drseden-Rossendorf, Forschungszentrum Jülich
#
# SPDX-License-Identifier: CC0-1.0

# SPDX-FileContributor: Stephan Druskat

name: Software publication on Zenodo Sandbox

on:
  push:
    tags:
      - "*"

jobs:
  hermes:
    name: HERMES
    runs-on: ubuntu-latest
    permissions:
      contents: read # We will only read content from the repo
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # Install HERMES from GitHub
      - run: pip install git+https://github.com/hermes-hmc/workflow.git
      # Archive everything in the git repository into a zip file
      - run: git archive --format zip HEAD . > hermes.zip
      - run: hermes harvest
      - run: hermes process
      - run: hermes curate
      - run: hermes deposit --auth-token ${{ secrets.ZENODO_SANDBOX }} --file hermes.zip --file README.md
